title: GAB Docs
email: your-email@example.com
description: >-
  Glitch Art Bot documentation. A Twitter bot that glitches images
  on the fly with multiple options.
baseurl: ""
url: ""
twitter_username: GlitchArtBot
github_username: friaca

theme: minima
plugins:
  - jekyll-feed

collections:
  docs:
    output: true
