title: Glitch Art Bot
email: your-email@example.com
description: >-
  Glitch Art Bot documentation. A Twitter bot that glitches images
  on the fly with multiple options.
baseurl: ""
url: ""
twitter_username: GlitchArtBot
github_username: glitchartbot

theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  docs:
    output: true
    permalink: /:collection/:title
